version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  scheduler:
    image: apache/airflow
    command: scheduler
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
  webserver:
    build: .
    depends_on:
      - postgres
      - scheduler
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"

  trino:
    image: trinodb/trino:362
    environment:
      - TRINO_ENVIRONMENT=production
    ports:
      - "8081:8080"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - postgres
